#!/bin/sh

# Exit
argenctl binding set normal Super+Shift+Control E exit

# Terminal
argenctl binding set normal Super+Shift Return exec "contour"

# Spawn Apps
argenctl binding set normal Super Return sh "tofi-run | xargs fish -c"

# Window focus and swap
argenctl binding set normal Super J window focus prev
argenctl binding set normal Super K window focus next
argenctl binding set normal Super+Shift J window swap prev
argenctl binding set normal Super+Shift K window swap next

argenctl binding set normal Super F window fullscreen
argenctl binding set normal Super Space window float

argenctl binding set normal Super Q window close

# Output focus and send
argenctl binding set normal Super Period output focus next
argenctl binding set normal Super Comma output focus prev
argenctl binding set normal Super+Shift Period window send next
argenctl binding set normal Super+Shift Comma window send prev

# Layout
argenctl binding set normal Super H layout set primary-ratio -0.05
argenctl binding set normal Super L layout set primary-ratio +0.05
argenctl binding set normal Super+Control K layout set secondary-ratio -0.05
argenctl binding set normal Super+Control J layout set secondary-ratio +0.05

# Pointer
argenctl pointer-binding set normal Super BTN_LEFT move-window
argenctl pointer-binding set normal Super BTN_RIGHT resize-window
# I dont have middle button, possibly add different binding?
# argenctl pointer-binding set normal Super BTN_MIDDLE scroll

# Context
argenctl binding set normal Super+Shift+Control Q context close
argenctl binding set normal Super Tab context switch --last

# Switch contexts interactively
argenctl binding set normal Super Slash sh 'argenctl context switch "$(argenctl context list | fuzzel -d --only-match)"'

# Create new context interactively
argenctl binding set normal Super+Shift Slash sh '
    prompt="$(fuzzel -d --prompt-only "new > ")"
    argenctl context new "$prompt"
'

# Rename current context interactively
argenctl binding set normal Super+Control Slash sh '
    prompt="$(fuzzel -d --prompt-only "rename > ")"
    argenctl context rename "$prompt"
'

# Assign currently focused window to be toggled with Super U
argenctl binding set normal Super+Shift U sh '
    id=$(argenctl window list --json | jq -r ".[] | select(.focused) | .id")
    argenctl binding set normal Super U window toggle "$id"
'

argenctl binding set normal Super D window detach
# Attach window interactively
argenctl binding set normal Super+Shift D sh '
    id=$(argenctl window list | fuzzel -d --with-nth 2 --accept-nth 1 --only-match)
    argenctl window attach "$id"
'

# Adopt all orphans
argenctl binding set normal Super+Control D sh '
    argenctl window list --json | jq -r ".[] | select(.contexts | length == 0) | .id" | while read -r id; do
        argenctl window attach "$id"
    done
'

# Layouts
# argenctl binding set normal Super Minus layout switch prev
# argenctl binding set normal Super Equal layout switch next
argenctl binding set normal Super 1 layout switch stacktile
argenctl binding set normal Super 2 layout switch monocle
argenctl binding set normal Super 3 layout switch columns
argenctl binding set normal Super 4 layout switch scrolling

# Audio and brightness controls
VOL_DEC='wpctl set-volume @DEFAULT_SINK@ 5%-'
VOL_INC='wpctl set-mute @DEFAULT_SINK@ 0 && wpctl set-volume @DEFAULT_SINK@ --limit 1.5 5%+'
VOL_TOGGLE='wpctl set-mute @DEFAULT_SINK@ toggle'
for mode in normal locked; do
    argenctl binding set $mode None XF86AudioLowerVolume sh "$VOL_DEC"
    argenctl binding set $mode None XF86AudioRaiseVolume sh "$VOL_INC"
    argenctl binding set $mode None XF86AudioMute sh "$VOL_TOGGLE"

    argenctl binding set $mode None XF86MonBrightnessDown sh "brightnessctl s 5%-"
    argenctl binding set $mode None XF86MonBrightnessUp sh "brightnessctl s +5%"

	argenctl binding set $mode Super Minus sh "fish -c dark"
	argenctl binding set $mode Super Equal sh "fish -c dim"
	argenctl binding set $mode Super+Shift Equal sh "fish -c bright"
done

# Passthrough mode
argenctl mode declare passthrough
argenctl binding set normal Super Grave mode enter passthrough
argenctl binding set passthrough Super Grave mode enter normal

# Window rules
argenctl rule add no-tearing

# === STARTUP ===

# Config
argenctl exec "channel"

# Wallpaper
argenctl exec "awww-daemon"
awww img ~/Desktop/Desktop/Backgrounds/background_omon.jpg

# Waybar (change for zelbar?)
argenctl sh "fish -c rebar"
argenctl binding set normal Super r sh "fish -c rebar"

