#!/bin/sh

# Exiting
argenctl binding set normal Super+Shift+Control E exit

# Terminal
argenctl binding set normal Super+Shift Return exec "contour"

# Spawn Apps
argenctl binding set normal Super Return sh "tofi-run --font='FiracodeNerdFont' --font-size=11 --prompt-text='' --background-color=#1E1E2E --padding-top=10 | xargs fish -c"

# Output focus and send
argenctl binding set normal Super Period output focus next
argenctl binding set normal Super Comma output focus prev
argenctl binding set normal Super+Shift Period window send next
argenctl binding set normal Super+Shift Comma window send prev

# === LAYOUT / WINDOW ===

argenctl config set default-layout stacktile
argenctl config set stacktile inner-padding 3
argenctl config set stacktile outer-padding 5
argenctl config set monocle outer-padding 5
argenctl config set columns inner-padding 3
argenctl config set columns outer-padding 5
argenctl config set scrolling inner-padding 3
argenctl config set scrolling outer-padding 5

# Window focus and swap
argenctl binding set normal Super J window focus prev
argenctl binding set normal Super K window focus next
argenctl binding set normal Super+Shift J window swap prev
argenctl binding set normal Super+Shift K window swap next

argenctl binding set normal Super F window fullscreen
argenctl binding set normal Super Space window float

argenctl binding set normal Super Q window close

# Layout
argenctl binding set normal Super H layout set primary-ratio -0.05
argenctl binding set normal Super L layout set primary-ratio +0.05
argenctl binding set normal Super+Shift H layout set secondary-ratio -0.05
argenctl binding set normal Super+Shift L layout set secondary-ratio +0.05

# Pointer
argenctl pointer-binding set normal Super BTN_LEFT move-window
argenctl pointer-binding set normal Super BTN_RIGHT resize-window
argenctl pointer-binding set normal Super+Shift BTN_LEFT scroll

# Assign currently focused window to be toggled with Super I
argenctl binding set normal Super+Shift I sh '
    id=$(argenctl window list --json | jq -r ".[] | select(.focused) | .id")
    argenctl binding set normal Super I window toggle "$id"
'

# === Contexts ===

# Simple binds
argenctl binding set normal Super+Control Q context close
argenctl binding set normal Super Tab context switch --last

# Switch contexts interactively
argenctl binding set normal Super Slash sh 'argenctl context switch "$(argenctl context list | fuzzel -d --only-match)"'

# Create new context interactively
argenctl binding set normal Super+Control Slash sh '
    prompt="$(fuzzel -d --prompt-only "new > ")"
    argenctl context new "$prompt"
'

# Rename current context interactively
argenctl binding set normal Super+Control Comma sh '
    prompt="$(fuzzel -d --prompt-only "rename > ")"
    argenctl context rename "$prompt"
'

# === Adopting and Detaching ===

argenctl binding set normal Super D window detach

# Attach window interactively
argenctl binding set normal Super+Control D sh "
    id=\$(argenctl window list --json | jq -r '.[] | @json \"\\(.id)\\t\\(.title)\"' | fuzzel -w 60 -d --with-nth 2 --accept-nth 1 --only-match | tr -d '\"')
    argenctl window attach \$id
"

# Attach orphans interactively
argenctl binding set normal Super+Shift D sh "
    id=\$(argenctl window list --json | jq -r '.[] | select(.contexts | length == 0) | @json \"\\(.id)\\t\\(.title)\"' | fuzzel -w 60 -d --with-nth 2 --accept-nth 1 --only-match | tr -d '\"')
    argenctl window attach \$id
"

# Adopt all orphans
argenctl binding set normal Super+Shift+Control D sh '
    argenctl window list --json | jq -r ".[] | select(.contexts | length == 0) | .id" | while read -r id; do
        argenctl window attach "$id"
    done
'

# Layouts
argenctl binding set normal Super 1 layout switch stacktile
argenctl binding set normal Super 2 layout switch monocle
argenctl binding set normal Super 3 layout switch columns
argenctl binding set normal Super 4 layout switch scrolling

# ALL MODE BINDINGS

# Audio and brightness controls
VOL_DEC='pamixer -d 5'
VOL_INC='pamixer -i 5'
VOL_TOGGLE='pamixer --toggle-mute'
for mode in normal locked; do
    argenctl binding set $mode None XF86AudioLowerVolume sh "$VOL_DEC"
    argenctl binding set $mode None XF86AudioRaiseVolume sh "$VOL_INC"
    argenctl binding set $mode None XF86AudioMute sh "$VOL_TOGGLE"

    argenctl binding set $mode None XF86MonBrightnessDown sh "brightnessctl s 5%-"
    argenctl binding set $mode None XF86MonBrightnessUp sh "brightnessctl s +5%"

	argenctl binding set $mode Super Minus sh "fish -c dark"
	argenctl binding set $mode Super Equal sh "fish -c dim"
	argenctl binding set $mode Super+Shift Equal sh "fish -c bright"
done

# Passthrough mode
argenctl mode declare passthrough
argenctl binding set normal Super Grave mode enter passthrough
argenctl binding set passthrough Super Grave mode enter normal

# Window rules
argenctl rule add no-tearing

# === SCRIPT BINDS ===

argenctl binding set normal Super P sh "~/Dots/scripts/screenshot.sh region"

argenctl binding set normal Super Escape sh "~/Dots/scripts/lock.sh"

# === STARTUP ===

# Config
argenctl exec "channel"

# Wallpaper
argenctl exec "awww-daemon"
awww img ~/Desktop/Desktop/Backgrounds/background_omon.jpg

# Waybar (change for zelbar?)
argenctl sh "fish -c rebar"
argenctl binding set normal Super r sh "fish -c rebar"

# Idle
argenctl sh "swayidle before-sleep 'true'"

# Network
argenctl sh nm-applet

