
# Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shell
set-option -g default-shell /bin/fish

# Mouse
set -g mouse on

# History
set -g history-limit 10000

# Indexing
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Binds


# Colors and Statusline
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
# Primarily from Gruvbox Dark
set-option -g status on
set-option -g status-style bg=colour237,fg=colour223
set-window-option -g window-status-style bg=colour214,fg=colour237
set-window-option -g window-status-activity-style bg=colour237,fg=colour248
set-window-option -g window-status-current-style bg=colour214,fg=colour237
set-option -g pane-active-border-style fg=colour250
set-option -g pane-border-style fg=colour237
set-option -g message-style bg=colour239,fg=colour223
set-option -g message-command-style bg=colour248,fg=colour237
set-option -g display-panes-active-color colour250
set-option -g display-panes-color colour237
set-window-option -g clock-mode-color colour109
set-window-option -g window-status-bell-style bg=colour167,fg=colour235
set-option -g status-justify left
#set-option -g status-left-length 80
set-option -g status-right-length 80
set-window-option -g window-status-separator ""
set-option -g status-left "#{?client_prefix,#[bg=colour223]#[fg=colour241] PREFIX #[bg=colour239]#[fg=colour223]#[nobold]#[noitalics]#[nounderscore],#[bg=colour241]#[fg=colour223] prefix #[bg=colour239]#[fg=colour241]#[nobold]#[noitalics]#[nounderscore]}"
set-option -g status-right "#[bg=colour237,fg=colour239,nobold,nounderscore,noitalics]#[bg=colour239,fg=colour246] %Y-%m-%d  %H:%M #[bg=colour239,fg=colour248,nobold,noitalics,nounderscore]#[bg=colour248,fg=colour237] #{user} "
set-window-option -g window-status-current-format "#[bg=colour214,fg=colour237,nobold,noitalics,nounderscore]#[bg=colour214,fg=colour239] #I #[bg=colour214,fg=colour239,bold] #W#{?window_zoomed_flag,*Z,} #{?window_end_flag,#[bg=colour237],#[bg=colour237]}#[fg=colour214,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=colour239,fg=colour237,noitalics]#[bg=colour239,fg=colour223] #I #[bg=colour239,fg=colour223] #W #{?window_end_flag,#[bg=colour237],#[bg=colour237]}#[fg=colour239,noitalics]"

